venv_dirpath: ".venv"

env:
  A: "1"
  B: "2"

packages:
  - name: "ruff"
    args: ["check", "--fix"]
  - name: "bandit"
    args: ["-r", "."]
    enabled: false
  - name: "checkov"
    args: ["--directory", "."]
