name: Tests

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-data:
    name: Test
    runs-on: ubuntu-24.04
    if: ${{ github.head_ref != 'release-please--branches--main' }} # Skip release-please branch
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Setup Uv
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: |
            uv.lock
            pyproject.toml

      - name: Run tests
        run: |
          echo "Pipeline info"
          echo "  - OS: $(uname -mo)"
          echo "  - UV version: ${{ steps.setup-uv.outputs.uv-version }}"
          echo "  - Python version: ${{ steps.setup-python.outputs.python-version}}"

          uv sync --all-extras

          uv run pre-commit run --all-files
          uv run pytest tests/parser.py
          py_secscan -vv scan
